# -*- coding: utf-8 -*-
"""hand_gesture_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YHV5F5kmkmaUn-jBNN8kjsIv_nmfK_D3
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install protobuf==5.29.5
!pip install tensorflow==2.19.0
!pip install mediapipe==0.10.21

import google.protobuf
print("protobuf:", google.protobuf.__version__)

import mediapipe as mp
print("mediapipe:", mp.__version__)

mp_hands = mp.solutions.hands
print("OK!")

import zipfile
import os

# CHANGE THIS to match your actual zip file path from Step 2
ZIP_PATH = '/content/drive/MyDrive/gesture_subset.zip'

# Unzip to Colab's LOCAL storage (much faster than Drive)
EXTRACT_PATH = '/content/dataset'

print("Unzipping... (this may take a few minutes for 2.66GB)")
with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
    zip_ref.extractall(EXTRACT_PATH)
print("Done!")

# Check what got extracted
for item in os.listdir(EXTRACT_PATH):
    print(item)

import os

# The folder structure might be nested — let's find the gesture folders
EXTRACT_PATH = '/content/dataset'

def find_gesture_folders(path, depth=0):
    """Recursively look for the gesture folders."""
    if depth > 3:
        return
    items = sorted(os.listdir(path))
    for item in items:
        full_path = os.path.join(path, item)
        if os.path.isdir(full_path):
            # Check if this looks like a gesture folder
            sub_items = os.listdir(full_path)
            has_avi = any(f.endswith('.avi') for f in sub_items)
            if has_avi:
                print(f"  GESTURE FOLDER: {full_path} ({len(sub_items)} files)")
            else:
                print(f"  Folder: {full_path}")
                find_gesture_folders(full_path, depth + 1)

print("Looking for gesture folders...\n")
find_gesture_folders(EXTRACT_PATH)

import cv2
import os

DATASET_PATH = '/content/dataset/gesture_subset'
FRAMES_DIR = '/content/frames'
FRAMES_PER_VIDEO = 30

gesture_classes = sorted([
    f for f in os.listdir(DATASET_PATH)
    if os.path.isdir(os.path.join(DATASET_PATH, f))
])

print("Extracting frames from videos...")

for gesture in gesture_classes:
    video_folder = os.path.join(DATASET_PATH, gesture)
    frames_folder = os.path.join(FRAMES_DIR, gesture)
    os.makedirs(frames_folder, exist_ok=True)

    video_files = [f for f in os.listdir(video_folder) if f.lower().endswith('.avi')]

    for video_file in video_files:
        video_path = os.path.join(video_folder, video_file)
        cap = cv2.VideoCapture(video_path)

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total_frames == 0:
            print(f"  WARNING: {video_file} has 0 frames, skipping")
            continue

        num_to_extract = min(FRAMES_PER_VIDEO, total_frames)
        frame_indices = set([
            int(i * total_frames / num_to_extract)
            for i in range(num_to_extract)
        ])

        frame_count = 0
        saved_count = 0

        while True:
            ret, frame = cap.read()
            if not ret:
                break
            if frame_count in frame_indices:
                video_name = video_file.replace('.avi', '')
                frame_filename = f"{video_name}_frame{saved_count:03d}.jpg"
                save_path = os.path.join(frames_folder, frame_filename)
                cv2.imwrite(save_path, frame)
                saved_count += 1
            frame_count += 1

        cap.release()

    frame_total = len(os.listdir(frames_folder))
    print(f"  {gesture}: {len(video_files)} videos -> {frame_total} frames")

import mediapipe as mp
import cv2
import numpy as np
import os

mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=True,
    max_num_hands=1,
    min_detection_confidence=0.5
)

FRAMES_DIR = '/content/frames'

gesture_classes = sorted([
    f for f in os.listdir(FRAMES_DIR)
    if os.path.isdir(os.path.join(FRAMES_DIR, f))
])

all_landmarks = []
all_labels = []
skipped = 0

print("Extracting hand landmarks...")

for gesture in gesture_classes:
    frames_folder = os.path.join(FRAMES_DIR, gesture)
    frame_files = sorted([f for f in os.listdir(frames_folder) if f.endswith('.jpg')])
    detected = 0

    for frame_file in frame_files:
        frame_path = os.path.join(frames_folder, frame_file)
        image = cv2.imread(frame_path)
        if image is None:
            continue

        rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = hands.process(rgb)

        if results.multi_hand_landmarks:
            landmarks = results.multi_hand_landmarks[0]
            coords = []
            for lm in landmarks.landmark:
                coords.append(lm.x)
                coords.append(lm.y)
                coords.append(lm.z)

            all_landmarks.append(coords)
            all_labels.append(gesture)
            detected += 1
        else:
            skipped += 1

    print(f"  {gesture}: {detected} hands detected (out of {len(frame_files)})")

hands.close()

X = np.array(all_landmarks)
y = np.array(all_labels)

print(f"\nTotal samples: {X.shape[0]}")
print(f"Skipped (no hand): {skipped}")
print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

import os
SAVE_PATH = '/content/drive/MyDrive/gesture_data'
os.makedirs(SAVE_PATH, exist_ok=True)

np.save(os.path.join(SAVE_PATH, 'X_landmarks.npy'), X)
np.save(os.path.join(SAVE_PATH, 'y_labels.npy'), y)

print(f"Saved to {SAVE_PATH}")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pickle

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print("Label mapping:")
for i, label in enumerate(label_encoder.classes_):
    print(f"  {i} = {label}")

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y_encoded, test_size=0.30, random_state=42, stratify=y_encoded
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

print(f"\nTrain: {X_train.shape[0]} samples")
print(f"Val:   {X_val.shape[0]} samples")
print(f"Test:  {X_test.shape[0]} samples")

for name, data in [('X_train', X_train), ('y_train', y_train),
                    ('X_val', X_val), ('y_val', y_val),
                    ('X_test', X_test), ('y_test', y_test)]:
    np.save(os.path.join(SAVE_PATH, f'{name}.npy'), data)

with open(os.path.join(SAVE_PATH, 'label_encoder.pkl'), 'wb') as f:
    pickle.dump(label_encoder, f)

print("Split and saved!")

import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import os

# Load data
SAVE_PATH = '/content/drive/MyDrive/gesture_data'
X_train = np.load(os.path.join(SAVE_PATH, 'X_train.npy'))
y_train = np.load(os.path.join(SAVE_PATH, 'y_train.npy'))
X_val = np.load(os.path.join(SAVE_PATH, 'X_val.npy'))
y_val = np.load(os.path.join(SAVE_PATH, 'y_val.npy'))

print(f"Train: {X_train.shape}, Val: {X_val.shape}")

# Build model
model = models.Sequential([
    # Input: 63 values (21 landmarks x 3 coords)
    layers.Input(shape=(63,)),

    # Reshape to (21, 3) — treat each landmark as a "step" with 3 features
    layers.Reshape((21, 3)),

    # 1D CNN layers — extract patterns between neighboring landmarks
    layers.Conv1D(64, kernel_size=3, activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.Conv1D(128, kernel_size=3, activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.Conv1D(256, kernel_size=3, activation='relu', padding='same'),
    layers.BatchNormalization(),

    # GRU layer — learn sequential relationships between landmarks
    layers.GRU(128, return_sequences=False),

    # Dense layers — final classification
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),

    # Output: 11 gesture classes
    layers.Dense(11, activation='softmax'),
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import os

SAVE_PATH = '/content/drive/MyDrive/gesture_data'
X_train = np.load(os.path.join(SAVE_PATH, 'X_train.npy'))
y_train = np.load(os.path.join(SAVE_PATH, 'y_train.npy'))
X_val = np.load(os.path.join(SAVE_PATH, 'X_val.npy'))
y_val = np.load(os.path.join(SAVE_PATH, 'y_val.npy'))

print(f"Original training samples: {X_train.shape[0]}")

# ─── DATA AUGMENTATION ───────────────────────────────────────
# Create noisy copies of training data at different levels

augmented_X = [X_train.copy()]  # Start with original clean data
augmented_y = [y_train.copy()]

# 1. Add jittered versions (microgravity simulation)
for jitter in [0.005, 0.01, 0.02, 0.03]:
    X_jittered = X_train + np.random.normal(0, jitter, X_train.shape)
    # Only clip x,y (not z)
    for i in range(21):
        X_jittered[:, i*3] = np.clip(X_jittered[:, i*3], 0, 1)
        X_jittered[:, i*3+1] = np.clip(X_jittered[:, i*3+1], 0, 1)
    augmented_X.append(X_jittered)
    augmented_y.append(y_train.copy())

# 2. Add scaled versions (simulate different distances from camera)
for scale in [0.9, 0.95, 1.05, 1.1]:
    X_scaled = X_train * scale
    for i in range(21):
        X_scaled[:, i*3] = np.clip(X_scaled[:, i*3], 0, 1)
        X_scaled[:, i*3+1] = np.clip(X_scaled[:, i*3+1], 0, 1)
    augmented_X.append(X_scaled)
    augmented_y.append(y_train.copy())

# 3. Add partially occluded versions (simulate gloves)
fingertip_indices = [4, 8, 12, 16, 20]
for num_hide in [1, 2, 3]:
    X_occluded = X_train.copy()
    # Randomly pick which tips to hide for each sample
    for j in range(len(X_occluded)):
        tips_to_hide = np.random.choice(fingertip_indices, num_hide, replace=False)
        for tip in tips_to_hide:
            X_occluded[j, tip*3] = 0
            X_occluded[j, tip*3+1] = 0
            X_occluded[j, tip*3+2] = 0
    augmented_X.append(X_occluded)
    augmented_y.append(y_train.copy())

# Combine all augmented data
X_train_aug = np.concatenate(augmented_X, axis=0)
y_train_aug = np.concatenate(augmented_y, axis=0)

# Shuffle
shuffle_idx = np.random.permutation(len(X_train_aug))
X_train_aug = X_train_aug[shuffle_idx]
y_train_aug = y_train_aug[shuffle_idx]

print(f"Augmented training samples: {X_train_aug.shape[0]} ({X_train_aug.shape[0] / X_train.shape[0]:.1f}x more data!)")

# Same model architecture
model_robust = models.Sequential([
    layers.Input(shape=(63,)),
    layers.Reshape((21, 3)),
    layers.Conv1D(64, kernel_size=3, activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.Conv1D(128, kernel_size=3, activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.Conv1D(256, kernel_size=3, activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.GRU(128, return_sequences=False),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(11, activation='softmax'),
])

model_robust.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train on AUGMENTED data
history = model_robust.fit(
    X_train_aug, y_train_aug,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=64,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(patience=15, restore_best_weights=True),
        tf.keras.callbacks.ReduceLROnPlateau(factor=0.5, patience=7),
    ]
)

# Evaluate
X_test = np.load(os.path.join(SAVE_PATH, 'X_test.npy'))
y_test = np.load(os.path.join(SAVE_PATH, 'y_test.npy'))
test_loss, test_acc = model_robust.evaluate(X_test, y_test)
print(f"\nRobust Model Test Accuracy: {test_acc*100:.2f}%")

# Save
model_robust.save(os.path.join(SAVE_PATH, 'gesture_model_robust.h5'))
print("Robust model saved!")

# Test accuracy
X_test = np.load(os.path.join(SAVE_PATH, 'X_test.npy'))
y_test = np.load(os.path.join(SAVE_PATH, 'y_test.npy'))

test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"\nTest Accuracy: {test_accuracy * 100:.2f}%")

# Save model to Drive
model.save(os.path.join(SAVE_PATH, 'gesture_model.h5'))
print("Model saved!")

# Plot training history
import matplotlib.pyplot as plt

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

ax1.plot(history.history['accuracy'], label='Train')
ax1.plot(history.history['val_accuracy'], label='Validation')
ax1.set_title('Accuracy')
ax1.legend()

ax2.plot(history.history['loss'], label='Train')
ax2.plot(history.history['val_loss'], label='Validation')
ax2.set_title('Loss')
ax2.legend()

plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

# Load label encoder
with open(os.path.join(SAVE_PATH, 'label_encoder.pkl'), 'rb') as f:
    label_encoder = pickle.load(f)

# Predict on test set
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Classification report
print("Classification Report:")
print(classification_report(y_test, y_pred_classes,
      target_names=label_encoder.classes_))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_classes)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)
plt.title('Confusion Matrix - Test Set)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.savefig(os.path.join(SAVE_PATH, 'confusion_matrix.png'), dpi=150)
plt.show()